# Generated by Django 5.0.1 on 2024-01-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=64)),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date')),
                ('end_datetime', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
    ]
