# Generated by Django 5.0.1 on 2024-01-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
