# Generated by Django 5.0.1 on 2024-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0002_rename_end_datetime_activity_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
