# Generated by Django 5.0.1 on 2024-01-16 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0004_alter_activity_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 20, 54, 21, 988069, tzinfo=datetime.timezone.utc), verbose_name='Start Date'),
        ),
    ]
